 # Create a 1-dimensional numpy array with shape (5,).

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.shape)


(5,)


# Create a 2-dimensional numpy array with shape (4,2).

In [3]:
arr = np.array(

   [
       [1,2],
       [1,2],
       [1,2],
       [1,2]
   ]
    )
print(arr.shape)

(4, 2)


# Create a 3-dimensional numpy array with shape (3,2,3).

In [4]:
arr = np.array(
    [
        [
            [2,3,4],[2,3,4]
        ],
        [
            [3,2,4],[3,2,4]
        ],
        [
            [5,8,6],[3,2,4]
        ]
    ]
)
print(arr.shape)

(3, 2, 3)


# Create a 4-dimensional numpy array with shape (6,5,4,3).

In [5]:
array_4d = np.random.rand(6, 5, 4, 3)
print("Shape of the array:", array_4d.shape)
print("\n4D array:")
print(array_4d)

Shape of the array: (6, 5, 4, 3)

4D array:
[[[[9.43071036e-01 2.11341075e-01 8.33351282e-01]
   [6.87310851e-01 8.30581369e-02 9.00839704e-01]
   [8.33761223e-01 2.21099847e-01 4.97081424e-01]
   [5.14592916e-01 1.54999133e-01 1.25605330e-01]]

  [[7.10312950e-01 5.48361306e-02 7.54050003e-01]
   [7.23086006e-01 7.10116392e-04 4.82143050e-01]
   [5.77554408e-01 6.29221028e-01 8.39882033e-01]
   [1.52904533e-01 4.87371082e-01 5.79255493e-01]]

  [[5.72215987e-01 4.64445063e-01 7.38754908e-01]
   [9.95032451e-01 6.85691484e-01 8.17843901e-01]
   [7.91909181e-01 1.50033649e-01 9.48838512e-02]
   [5.64795140e-02 9.57101808e-01 7.18796457e-01]]

  [[2.31769514e-01 9.67135055e-01 9.72167127e-01]
   [2.49434649e-01 9.28904550e-01 5.12184248e-01]
   [6.52224474e-01 4.56622274e-01 9.89748793e-01]
   [3.62246462e-01 4.67337525e-01 4.18924191e-01]]

  [[2.74555895e-01 2.46190258e-01 6.66868179e-02]
   [1.39972427e-01 8.01715713e-01 1.37649493e-01]
   [8.77092720e-01 8.35406059e-01 8.33646183e-01

# Using numpy array indexing, update the value 11 to 12 and print the updated array.

In [8]:
arr = np.array(
[
[
[1, 2, 3],
[4, 5, 6]
],
[
[7, 8, 9],
[11, 13, 14]
]
]
)
arr[1, 1, 0] = 12


In [9]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [12 13 14]]]


# Using numpy array slicing, update the values 3, 6, 9, and 14 to 100 and print the updated array.

In [ ]:
arr = np.array(
[
[
[1, 2, 3],
[4, 5, 6]
],
[
[7, 8, 9],
[11, 13, 14]
]
]
)

arr[1, 1, 0] = 12

arr[:,:,2] = 100
print(arr)

[[[  1   2 100]
  [  4   5 100]]

 [[  7   8 100]
  [ 12  13 100]]]


# Create a dictionary representation of the table below and create a pandas DataFrame and print the resulting DataFrame.

In [10]:
import pandas as pd

data = {
    'Name': ['John', 'Alice', 'Bob', 'Eve'],
    'Age': [23, 17, 19, 18],
    'Score': [88, 92, 75, 89]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Score
0   John   23     88
1  Alice   17     92
2    Bob   19     75
3    Eve   18     89


# Show use cases (code examples) of .iloc and .loc for selecting data from the DataFrame.

In [11]:
# Select the second row (index position 1)
row1 = df.iloc[1]
print(row1)


Name     Alice
Age         17
Score       92
Name: 1, dtype: object


In [12]:
name_score_columns = df.loc[:, ['Name', 'Score']]
print("\nUsing .loc to select the 'Name' and 'Score' columns:")
print(name_score_columns)


Using .loc to select the 'Name' and 'Score' columns:
    Name  Score
0   John     88
1  Alice     92
2    Bob     75
3    Eve     89


# Filter and print the rows where Age is greater than or equal to 18.

In [13]:
adults = df.loc[df['Age'] >= 18]
print(adults)

   Name  Age  Score
0  John   23     88
2   Bob   19     75
3   Eve   18     89
